version: "3.8"

networks:
  app-tier:
    driver: bridge

services:

  frontend:
    container_name: wave-tech-frontend
    build:
      context: ./fontend
    ports:
      - "3000:3000"
    networks:
      - app-tier

  backend:
    container_name: wave-tech-backend
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; npm start'
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      NODE_ENV: development
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wave-tech-db
      MYSQL_ROOT_HOST: '%'
    networks:
      - app-tier
    links:
      - database
    volumes:
      - ./:/src

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=wave-tech-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=ok
    ports:
      - "3306:3306"
    networks:
      - app-tier
    expose:
      - 3306
    volumes:
      - ./ehealth:/var/lib/mysql

volumes:
  ehealth:
